config/routes.rb
Rails.application.routes.draw do
  root to: 'site#index'
  devise_for :users
  
  get 'site/purchase'
  get 'site/buy_product', 'site#buy_product'
  get 'site/transfer'
  post 'site/transfer_money', 'site#transfer_money'
  # get 'site/download_product'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :user_relationships, foreign_key: 'user_id'
  has_many :related_users, through: :user_relationships
  
  attr_accessor :money
  before_validation :set_default_money, on: :create

  def set_default_money
    self.money ||= 1
  end

  def money
    self[:money]
  end

  def money=(value)
    self[:money] = value
  end
  validates :money, presence: true, numericality: { greater_than_or_equal_to: 0 }
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user_relationship.rb
class UserRelationship < ApplicationRecord
	belongs_to :user
	belongs_to :related_user, class_name: 'User', foreign_key: 'related_user_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  skip_before_action :verify_authenticity_token
  helper_method :redirect_to
  def index
  end

  def product
  end

  def buy_product
    if current_user.money >= 10
      current_user.money -= 10
      current_user.save
      send_file(
        "#{Rails.root}/PasswordGenerator",
        filename: "PasswordGenerator",
        type: "application/octet-stream"
      )
      flash[:success] = "You have successfully purchased the product."
      
    else
      redirect_to :site_purchase, notice: "You don't have enough money to purchase the product."
    end
  end

  def transfer_money
    if user_signed_in?
      email = params.require(:email)
      amount = params.require(:amount)
      
      # check if email matches revworks.thm and amount is integer
      if email.match(/\A([\w+\-].?)+@revworks\.thm\z/) and amount.match(/\A[+-]?\d+\z/)

        # check if amount is negative, because otherwise user transfers negative value
        # which increments his own amount. amount - (-value)
        if amount.to_i < 0
          redirect_to :site_transfer, notice: "You can not transfer negative amount to another user."

        # check if user has the amount to transfer
        elsif amount.to_i > current_user.money
          redirect_to :site_transfer, notice: "You don't have enough money to transfer."
        else

          # check if user exists
          if User.find_by_email(email).nil?
            redirect_to :site_transfer, notice: "User doesn't exist."
          else
            # check if user isn't himself
            if User.find_by_email(email) == current_user
              redirect_to :site_transfer, notice: "Silly, You can't transfer money to yourself."
            else
              # check if it's only to/from the same one user
              user = User.find_by(email: email)
              if user.related_users.count < 1 and !user.related_users.map(&:email).include? current_user.email
                # Add the new relationship
                UserRelationship.create(user_id: user.id, related_user_id: current_user.id)

                # transfer money
                current_user.money -= amount.to_i
                current_user.save
                user.money += amount.to_i
                user.save
                redirect_to :site_transfer, notice: "You have successfully transferred money to #{email}."

              elsif user.related_users.map(&:email).include? current_user.email
                # transfer money
                current_user.money -= amount.to_i
                current_user.save
                user.money += amount.to_i
                user.save
                redirect_to :site_transfer, notice: "You have successfully transferred money to #{email}."

              else
                redirect_to :site_transfer, notice: "User can only send/recieve from one user right now."
              end
            end
          end
        end
      else
        flash[:danger] = "Invalid email domain, please use revworks.thm"
        redirect_to :site_transfer
      end
    
    else
      redirect_to new_user_session_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ActionController::Base
	def show
  		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <title>Revworks</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/site/index.html.erb
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="icon" type="image/x-icon" href="https://i.imgur.com/PL9uJDp.png">

<title>Welcome - revworks.thm</title>
<%= stylesheet_link_tag 'style', media: 'all' %>
<%= stylesheet_link_tag 'https://use.fontawesome.com/releases/v5.1.0/css/all.css', integrity: 'sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt', crossorigin: 'anonymous' %>
<%= stylesheet_link_tag 'jquery.fancybox.min', 'owl.carousel.min', 'owl.theme.default.min', media: 'all' %>


<!-- Font Google -->
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">

<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<%= stylesheet_link_tag 'bootstrap.css' %>
<body>
<!-- Navbar -->
<nav class="navbar navbar-expand-lg">
  <div class="container"> <%= image_tag "logo.png", alt: "logo", class: "navbar-brand navbar-logo logo-1" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"> <span class="fas fa-bars"></span> </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item"> <a class="nav-link" href="#" data-scroll-nav="0">About</a> </li>
        <li class="nav-item"> <a class="nav-link" href="#" data-scroll-nav="1">Contact</a> </li>

        <!-- custom code -->
        <% if user_signed_in? %>
          <% flash.each do |type, msg| %>
              <% sleep(0) %>
          <% end %>
          </br>
        <strong>Money: <%= current_user.money.to_i %> </strong>&nbsp;&nbsp;
        <div class="dropdown" style="display:inline-block;">
          <button id="options-btn" class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown"><strong><%= current_user.email %></strong>
          <span class="caret"></span></button>
          <ul class="dropdown-menu" style="text-align: center;">
            <%= link_to 'purchase', site_purchase_path, method: :get, :class => 'navbar-link' %><br>
            <%= link_to 'transfer', site_transfer_path, method: :get, :class => 'navbar-link' %><br>
            <%= link_to 'Edit profile', edit_user_registration_path, method: :get, :class => 'navbar-link' %><br>
            <%= button_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          </ul>
        </div>
        
      <% else %>&nbsp;&nbsp;
        <%= link_to "Sign up", new_user_registration_path, method: :get, :class => 'navbar-link'  %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <%= link_to "Login", user_session_path, :class => 'navbar-link'  %>
      <% end %>
      </ul>
    </div>
  </div>
</nav>
<!-- End Navbar --> 

<!-- Banner Image -->

<div class="banner text-center" data-scroll-index='0'>
  <div class="banner-overlay">
    <div class="container">
      <h1 class="text-capitalize">Creative Business for Reversing and Analysis  </h1>
      <a href="#" class="banner-btn">Get Started</a> </div>
  </div>
</div>

<!-- End Banner Image --> 

<!-- About -->

<div class="about-us section-padding" data-scroll-index='1'>
  <div class="container">
    <div class="row">
      <div class="col-md-12 section-title text-center">
        <h3 style="background-color: darkgrey;"><strong>We Are Best At Our Work</strong></h3>
        <span class="section-title-line"></span> </div>
      <div class="col-md-6 mb-50">
        <div class="section-info">
          <div class="sub-title-paragraph">
            <h4>You can conquer the world.</h4>
          </div>
          <a href="#" class="anchor-btn">Learn more <i class="fas fa-arrow-right pd-lt-10"></i></a> </div>
      </div>
      <div class="col-md-6 mb-50">
        <div class="section-img"> <%= image_tag 'about.jpg', alt: 'about', class: 'img-responsive' %> </div>
      </div>
    </div>
  </div>
</div>

<!-- End About --> 

<!-- Services -->
<div class="services section-padding bg-grey" data-scroll-index='2'>
  <div class="container">
    <div class="row">
      <div class="col-md-12 section-title text-center">
        <h3>We Are Best At Our Service</h3>
        <span class="section-title-line"></span> </div>
    </div>
  </div>
</div>

<!-- End Services --> 
<!-- Testimonials -->
<div class="testimonials">
  <div class="testimonials-overlay section-padding">
    <div class="container">
      <div class="row">
        <div class="col-md-10 offset-md-1">
          <div class="owl-carousel owl-theme">
            <div class="testimonial-item text-center">
              <div class="icon"> <i class="fas fa-comments"></i> </div>
              <p class="m-auto">See this website you're on right now? You can give a big thanks to Stephen for creating it and making it available online.</p>
              <div class="testimonial-author text-center">
                <h5>Stephen Larson</h5>
                <h6>System Administrator</h6>
              </div>
            </div>
            <div class="testimonial-item text-center">
              <div class="icon"> <i class="fas fa-comments"></i> </div>
              <p class="m-auto">Adam defines what revworks is and is Founder and CEO. Adam started the company with just 10 other people!</p>
              <div class="testimonial-author text-center">
                <h5>Adam Doupe</h5>
                <h6>Founder, CEO</h6>
              </div>
            </div>
            <div class="testimonial-item text-center">
              <div class="icon"> <i class="fas fa-comments"></i> </div>
              <p class="m-auto">Christopher has been with revworks since the begining, and once he started, we have never let him go.</p>
              <div class="testimonial-author text-center">
                <h5>Christopher jones</h5>
                <h6>Web Desinger</h6>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- End Testimonials --> 

<!-- Contact -->
<div class="contact section-padding" data-scroll-index='4'>
  <div class="container">
    <div class="row">
      <div class="col-md-12 section-title text-center">
        <h3 style="background-color: whitesmoke;"><strong>Contact Us For More</strong></h3>
        <span class="section-title-line"></span> </div>
      <div class="col-lg-5 col-md-4">
        <div class="part-info">
          <div class="info-box">
            <div class="icon"> <i class="fas fa-phone"></i> </div>
            <div class="content">
              <h4>Phone :</h4>
              <p>0123456789</p>
            </div>
          </div>
          <div class="info-box">
            <div class="icon"> <i class="fas fa-map-marker-alt"></i> </div>
            <div class="content">
              <h4>Address :</h4>
              <p>New Delhi, India</p>
            </div>
          </div>
          <div class="info-box">
            <div class="icon"> <i class="fas fa-envelope"></i> </div>
            <div class="content">
              <h4>Mail :</h4>
              <p><a href="#">info@revworks.thm</a></p>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-7 col-md-8">
        <div class="contact-form">
          <form class='form' id='contact-form' method='post' data-toggle='validator'>
            <input type='hidden' name='form-name' value='contact-form' />
            <div class="messages"></div>
            <div class="controls">
              <div class="row">
                <div class="col-lg-6">
                  <div class="form-group">
                    <input id="form_name" type="text" name="name" placeholder="Name *" required data-error="name is required.">
                    <div class="help-block with-errors"></div>
                  </div>
                </div>
                <div class="col-lg-6">
                  <div class="form-group">
                    <input id="form_email" type="email" name="email" placeholder="Email *" required data-error="Valid email is required.">
                    <div class="help-block with-errors"></div>
                  </div>
                </div>
                <div class="col-lg-12">
                  <div class="form-group">
                    <input id="form_subject" type="text" name="subject" placeholder="Subject">
                  </div>
                </div>
                <div class="col-lg-12 form-group">
                  <textarea id="form_message" name="message" class="form-control" placeholder=" Type Your Message " rows="4" required data-error="Please,leave us a message."></textarea>
                  <div class="help-block with-errors"></div>
                </div>
                <div class="col-lg-12 text-center">
                  <button class="bttn">Send Message</button>
                </div>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- End Contact -->
<footer class="footer-copy">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <p>2018 &copy; Elegant. Website Designed by <a href="http://w3Template.com" target="_blank" rel="dofollow">W3 Template</a></p>
      </div>
    </div>
  </div>
</footer>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script> 
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script> 
<!-- owl carousel js --> 
<%= javascript_include_tag "owl.carousel.min" %>
<!-- magnific-popup --> 
<%= javascript_include_tag "jquery.fancybox.min" %>

<!-- scrollIt js --> 
<%= javascript_include_tag "scrollIt.min" %>

<!-- isotope.pkgd.min js --> 
<%= javascript_include_tag "isotope.pkgd.min" %>
<script>
  $(window).on("scroll",function () {

      var bodyScroll = $(window).scrollTop(),
          navbar = $(".navbar");

      if(bodyScroll > 130){

          navbar.addClass("nav-scroll");
          $('.navbar-logo img').attr('src','images/logo.png');


      }else{

          navbar.removeClass("nav-scroll");
          $('.navbar-logo img').attr('src','images/logo.png');

      }

  });

  $(window).on("load",function (){



var bodyScroll = $(window).scrollTop(),
navbar = $(".navbar");

if(bodyScroll > 130){

navbar.addClass("nav-scroll");
$('.navbar-logo img').attr('src','images/logo-black.png');


}else{

navbar.removeClass("nav-scroll");
$('.navbar-logo img').attr('src','images/logo-white.png');

}

/* smooth scroll
  -------------------------------------------------------*/
  $.scrollIt({

easing: 'swing',      // the easing function for animation
scrollTime: 900,       // how long (in ms) the animation takes
activeClass: 'active', // class given to the active nav element
onPageChange: null,    // function(pageIndex) that is called when page is changed
topOffset: -63
});

/* isotope
-------------------------------------------------------*/
var $gallery = $('.gallery').isotope({});
$('.gallery').isotope({

    // options
    itemSelector: '.item-img',
    transitionDuration: '0.5s',

});


$(".gallery .single-image").fancybox({
  'transitionIn'  : 'elastic',
  'transitionOut' : 'elastic',
  'speedIn'   : 600,
  'speedOut'    : 200,
  'overlayShow' : false
});


/* filter items on button click
-------------------------------------------------------*/
$('.filtering').on( 'click', 'button', function() {

    var filterValue = $(this).attr('data-filter');

    $gallery.isotope({ filter: filterValue });

    });

$('.filtering').on( 'click', 'button', function() {

    $(this).addClass('active').siblings().removeClass('active');

});

})

$(function () {
$( ".cover-bg" ).each(function() {
    var attr = $(this).attr('data-image-src');

    if (typeof attr !== typeof undefined && attr !== false) {
      $(this).css('background-image', 'url('+attr+')');
    }

  });

  /* sections background color from data background
  -------------------------------------------------------*/
  $("[data-background-color]").each(function() {
      $(this).css("background-color", $(this).attr("data-background-color")  );
  });


/* Owl Caroursel testimonial
  -------------------------------------------------------*/
  
  $('.testimonials .owl-carousel').owlCarousel({
    loop:true,
    autoplay:true,
    items:1,
    margin:30,
    dots: true,
    nav: false,
    
  });

});

</script>
</body>
</html>

app/views/site/purchase.html.erb
<!DOCTYPE html>
<html>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<%= stylesheet_link_tag 'bootstrap.css' %>
<% if user_signed_in? %>
	<% flash.each do |type, msg| %>
	  <div class="alert alert-info">
	  	<%= msg %>
	  </div>
	<% end %>

	</br><p style="text-align: right;"><%= link_to 'home', root_path, method: :get, :class => 'navbar-link' %>&nbsp;&nbsp;<strong class="text-light">Money: <%= current_user.money.to_i %> </strong>&nbsp;&nbsp;</p>
	<h1 style="text-align: center;">Product Page</h1>

	<!-- table -->
	<div class="container text-center text-dark bg-white">
        	<table class="table table-stripped table-bordered">
                <tbody>
                    <tr>
                        <th>
                            Item
                        </th>
                        <th>
                            Description
                        </th>
                        <th>
                            Price
                        </th>
                        <th>
                            Buy
                        </th>
                    </tr>
                    <tr>
                        <td style="text-align: center;">
                            Password Generator
                        </td>
                        <td style="text-align: center;">
                            This is our premium password generator. It gives you access to some juicy extra features to play with!<br>
                            What's that? You want to know what the features are? It's a surprise...
                        </td>
                        <td style="text-align: center;">
                            10
                        </td>
                        <td>
                            <%= button_to "Buy", site_buy_product_path, method: :get %>
							</script>
                        </td>
                    </tr>
                </tbody>
            </table>
    </div>
<% else %>
	<% redirect_to :new_user_session %>
<% end %>
</html>

app/views/site/transfer.html.erb
<!DOCTYPE html>
<html>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<%= stylesheet_link_tag 'bootstrap.css' %>
<% if user_signed_in? %>
    <% flash.each do |type, msg| %>
      <div class="alert alert-info">
        <%= msg %>
      </div>
    <% end %>
    </br>
    <p style="text-align: right;" class="text-light"><%= link_to 'home', root_path, method: :get, :class => 'navbar-link' %>&nbsp;&nbsp;
    <strong>Money: <%= current_user.money.to_i %> </strong>&nbsp;&nbsp;<strong><%= current_user.email %></strong></p>
    <div class="container text-center pt-5  bg-light bg-gradient">
        <h2 class="pb-3">Transfer Money</h2>
        <p>Here you can transfer money to other users. Use the form below:</p>
        <p>Note: Right now, you can only send/recieve to/from one other user.</p>
        
        <form action="/site/transfer_money" method="POST">
            <label for="email">Email:</label>

            <input class="form-control mb-3" type="text" name="email" id="uname">

            <label for="amnt">Amount:</label>

            <input class="form-control mb-3" type="number" name="amount" id="amnt">

            <input class="btn btn-primary btn-block mb-2" type="submit" value="Transfer">
        </form>
    </div>
	
<% else %>
	<% redirect_to :new_user_session %>
<% end %>
</body>
</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>